---
roles:
  - name: nephelaiio.postgresql_repo
  - name: robertdebock.update
collections:
  - name: nephelaiio.plugins
  - name: community.docker
  - name: ansible.posix
  - name: community.general
  - name: community.postgresql
